import { Inter } from "next/font/google";
import "@/app/globals.css";
import Navbar from "../(components)/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Admin",
  description: "Generated by create next app",
};

export default function AdminPageLayout({
  children, // will be a page or nested layout
}) {
  return (
    <body>
      <Navbar></Navbar>
      {/* Include shared UI here e.g. a header or sidebar */} 
      {children}
    </body>
  )
}
