import { Inter } from "next/font/google";
import "./globals.css";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <Script src="~bootstrap/dist/js/bootstrap.min.js"></Script> */}
      <body className="">
        <head>
          <link rel="stylesheet" href="assets/css/fontawesome.css" />
          <link rel="stylesheet" href="assets/css/templatemo-scholar.css" />
          <link rel="stylesheet" href="assets/css/owl.css" />
          <link rel="stylesheet" href="assets/css/animate.css" />
          <link
            rel="stylesheet"
            href="https://unpkg.com/swiper@7/swiper-bundle.min.css"
          />
        </head>
        {/* <h1>Root layout</h1> */}
        {children}

        <link rel="stylesheet" href="assets/css/nucleo-svg.css" />
        <link rel="stylesheet" href="assets/css/nucleo-icons.css" />
        <link rel="stylesheet" href="assets/css/flex-slider.css" />
        <link rel="stylesheet" href="assets/css/material-dashboard.css" />
        <link rel="stylesheet" href="assets/css/material-dashboard.css.map" />

        <Script
          src="https://kit.fontawesome.com/42d5adcbca.js"
          crossorigin="anonymous"
        />
        <link
          href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700"
          rel="stylesheet"
        />

        <link
          id="pagestyle"
          href="assets/css/material-dashboard.css"
          rel="stylesheet"
        />
      </body>
    </html>
  );
}
